apiVersion: apps/v1

kind: Deployment

metadata:
  name: poc-nestjs-deployment

  labels:
    app: poc-nestjs

spec:
  replicas: 1

  selector:
    matchLabels:
      app: poc-nestjs

  template:
    metadata:
      labels:
        app: poc-nestjs

    spec:
      containers:
        - name: poc
          image: poc-nestjs
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
      terminationGracePeriodSeconds: 20